map_topic: /map

#robot_laser_topic: /inner/sonar_measurements
robot_laser_topic: /robot0/laser_1

#only when stdr is used
laser_param: robot0_laser_1

#only when stdr is used
robot_param: robot0

#velocity_topic: /inner/cmd_vel
velocity_topic: /robot0/cmd_vel

rays_subsampling_step: 1

strictness: 1
 
particles_number: 10000
 
a1: 0.07
 
a2: 0.02
 
duration: 1

enable_visualization: true

rfid_reader_topic: /robot0/rfid_reader_0
#rfid_reader_topic: /inner/qr_detection

#only when stdr is used
rfid_tags_topic: /stdr_server/rfid_list

initial_pose_known: false

initial_x: 15

initial_y: 15

initial_theta: 0

stdr_used: true

rfid_reader_exists: true
