map_topic: /map

robot_laser_topic: /robot0/laser_1

laser_param: robot0_laser_1

robot_param: robot0

velocity_topic: /robot0/cmd_vel

rays_subsampling_step: 1

strictness: 1.5

particles_number: 10000

enable_visualization: true

a1: 0.1

a2: 0.05

duration: 1

rfid_reader_topic: /robot0/rfid_reader_0

rfid_tags_topic: /stdr_server/rfid_list
