map_topic: /map

robot_laser_topic: /robot0/laser_0

velocity_topic: /robot0/cmd_vel

rays_subsampling_step: 60

strictness: 0.7

particles_number: 1000

enable_visualization: true

a1: 0.1

a2: 0.05

duration: 5

rfid_reader_topic: /robot0/rfid_reader_0

rfid_tags_topic: /stdr_server/rfid_list
