map_topic: /map

#robot_laser_topic: /inner/sonar_measurements
robot_laser_topic: /robot0/laser_1

laser_param: robot0_laser_1

robot_param: robot0

#velocity_topic: /inner/cmd_vel
velocity_topic: /robot0/cmd_vel

rays_subsampling_step: 1

strictness: 0.8

particles_number: 10000

enable_visualization: true

a1: 0.1
#a1: 0
a2: 0.05
#a2: 0
duration: 1

rfid_reader_topic: /robot0/rfid_reader_0
#rfid_reader_topic: /inner/qr_detection

rfid_tags_topic: /stdr_server/rfid_list

initial_pose_known: false

initial_x: 10

initial_y: 7

initial_theta: 0

stdr_used: true

rfid_reader_exists: true
